version: "3.7"
services:
  app:
    image: app_name:1.0.0
    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: app_name
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - name

  # db:
  #   image: mariadb:10.11.7
  #   container_name: mysql_name
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   ports:
  #     - "3389:3306"
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
  #     - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - name
  
  nginx:
    image: nginx:1.26.0
    container_name: nginx_name
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - name
networks:
  name:
    # uncommet satu baris "driver: bridge" jika ada masalah dengan koneksi
    # driver: bridge

    # "db_service" bisa berubah sesuai dengan service mysql yang dijalankan melalui compose
    # jika menggunakan db diluar container seperti xampp atau lainnya, comment saja dua baris dibawah
    name: db_service
    external: true
